// v5 functional tests: credits, stages 8-10 (names, front-runners, Bear King), rocket ending + Moon Mode,
// share-to-X link, achievements (toast + view), skins (unlock gating + picker), local board moon icon. Zero console errors.
import { chromium } from 'playwright-core';
import { readFileSync } from 'node:fs';
const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, ''); // repo root
const CHROME = process.env.CHROME || '/usr/bin/google-chrome';
const URL0 = process.env.URL0 || 'file://' + ROOT + '/dist/decicat.html';
const b = await chromium.launch({ executablePath: CHROME });
const errs = []; let fails = 0;
const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) fails++; };
async function page(q, vp) { const ctx = await b.newContext({ viewport: vp || { width: 480, height: 480 } }); const p = await ctx.newPage(); p.on('pageerror', e => errs.push(q + ' ' + e.message)); p.on('console', m => { if (m.type() === 'error') errs.push(q + ' ' + m.text()); }); await p.goto(URL0 + q); await p.waitForTimeout(300); return p; }
const ev = (p, f, a) => p.evaluate(f, a);
const tapUI = async (p, k) => { const c = await ev(p, k => { const r = __decicat.ui[k]; return r && [r.x + r.w / 2, r.y + r.h / 2]; }, k); if (!c) return false; await ev(p, c => { __decicat.press(c[0], c[1]); __decicat.release(); __decicat.advance(2); }, c); return true; };

// 1. credits (source strings, play.html meta, no third-party tool credits)
{
  const html = readFileSync(ROOT + '/dist/decicat.html', 'utf8'), play = readFileSync(ROOT + '/server/play.html', 'utf8');
  ok(html.includes('ORIGINAL DECICAT CONCEPT BY @DONCASTRO.') && html.includes('GAME BY @ANGELATAPTOS'), 'credit strings in the game build');
  ok(play.includes('Original Decicat concept by @doncastro.') && !play.includes('Art & idea by @doncastro'), 'play.html meta credit updated');
  ok(play.includes('https://decicat.bitcade.xyz/play'), 'og:url is the bitcade domain');
  ok(!/(made with|generated by|powered by)/i.test(html + play), 'no third-party tool credits in the build or play page');
}
// 2. stage names / labels / Moon Mode
{
  const p = await page('?manual&nogate');
  const n = await ev(p, () => [8, 9, 10, 11, 13].map(z => __decicat.zoneName(z) + '/' + __decicat.stageLabel(z) + '/' + __decicat.ztype(z)));
  ok(n.join('|') === 'FRONT-RUNNER ALLEY/STAGE 8/9|BEAR KING/STAGE 9/10|LAUNCH PAD/STAGE 10/11|MOON MODE/MOON MODE/12|MOON MODE 3/MOON MODE/12', 'stages 8-10 + Moon Mode: ' + n.join(', '));
  await p.context().close();
}
// 3. front-runners spawn, lock a lane, and get outrun (bot+god in stage 8)
{
  const p = await page('?manual&autostart&bot&god&seed=4&zone=8');
  let seen = 0, locked = false; for (let i = 0; i < 300; i++) { await ev(p, () => __decicat.advance(4)); const s = await ev(p, () => __decicat.dbgShadows); if (s.length) seen++; if (s.some(q => q.w <= 0)) locked = true; }
  const st = await ev(p, () => __decicat.stats);
  ok(seen > 20 && locked, `front-runner shadows appear and run (${seen} samples)`);
  ok(st.bonus > 0, 'OUTRAN / stomp bonuses awarded (bonus ' + st.bonus + ')');
  await p.context().close();
}
// 4. Bear King: telegraphed phases, health bar, timeout retreat bonus or defeat
{
  const p = await page('?manual&autostart&bot&god&seed=3&zone=9&zt=14');
  const ph = new Set(); let minHp = 3;
  for (let i = 0; i < 230; i++) { await ev(p, () => __decicat.advance(4)); const B = await ev(p, () => __decicat.v5.boss); if (B) { ph.add(B.ph); minHp = Math.min(minHp, B.hp); } }
  ok(['throw', 'lunge', 'charge'].every(k => ph.has(k)) && (ph.has('wave') || ph.has('throw')), 'boss phases seen: ' + [...ph].join(','));
  ok(ph.has('retreat') || ph.has('flee'), 'boss leaves at the end (' + (ph.has('flee') ? 'defeated' : 'timeout retreat') + '), min hp ' + minHp);
  ok(await ev(p, () => __decicat.zone) >= 10, 'stage 10 follows the boss');
  await p.context().close();
}
// 5. ending: cutscene -> YOU MADE IT -> Moon Mode (watch and skip), result carries moon, local board moon flag
for (const mode of ['watch', 'skip']) {
  const p = await page('?manual&autostart&bot&god&seed=5&zone=10&zt=6');
  for (let i = 0; i < 200 && await ev(p, () => __decicat.state) === 'play'; i++) await ev(p, () => __decicat.advance(10));
  const v = await ev(p, () => ({ st: __decicat.state, v5: __decicat.v5, song: __decicat.audio && __decicat.audio.song }));
  ok(v.st === 'ending' && v.v5.reachedMoon && v.v5.endInfo && v.v5.endInfo.bonus === 10000, `${mode}: zone 10 end -> rocket cutscene, reachedMoon, +10000`);
  if (mode === 'skip') { await ev(p, () => { __decicat.advance(40); __decicat.press(); __decicat.release(); __decicat.advance(2); }); ok(await ev(p, () => __decicat.state) === 'moonwin', 'tap skips the cutscene'); await ev(p, () => { __decicat.advance(70); __decicat.press(); __decicat.release(); __decicat.advance(2); }); }
  else { await ev(p, () => __decicat.advance(Math.round(12.8 * 60))); ok(await ev(p, () => __decicat.state) === 'moonwin', 'cutscene ends on its own (~12.6 s)'); await ev(p, () => __decicat.advance(8.2 * 60)); }
  const m = await ev(p, () => ({ st: __decicat.state, z: __decicat.zone, lab: __decicat.stageLabel(__decicat.zone) }));
  ok(m.st === 'play' && m.z === 11 && m.lab === 'MOON MODE', `${mode}: Moon Mode starts (${JSON.stringify(m)})`);
  await ev(p, () => __decicat.advance(300));
  await p.context().close();
}
// 5b. real run to game over after the ending (no god): result.moon, share text, local board moon icon
{
  const p = await page('?nogate&manual&autostart&bot&seed=5&zone=10&zt=6&offline');
  await ev(p, () => __decicat.achReset());
  let st; for (let i = 0; i < 400; i++) { await ev(p, () => __decicat.advance(10)); st = await ev(p, () => __decicat.state); if (st === 'ending') { await ev(p, () => { __decicat.advance(40); __decicat.press(); __decicat.release(); __decicat.advance(80); __decicat.press(); __decicat.release(); }); } if (st === 'over' || st === 'dying') break; }
  if (st === 'play') await ev(p, () => __decicat.kill());
  for (let i = 0; i < 40 && await ev(p, () => !__decicat.result || __decicat.result.pending); i++) { await ev(p, () => __decicat.advance(10)); await p.waitForTimeout(50); }
  const r = await ev(p, () => ({ moon: __decicat.result.moon, z: __decicat.zone, txt: __decicat.shareText(), top: JSON.parse(localStorage.getItem('decicat_top10_v1') || '[]'), ach: __decicat.v5.ach }));
  const reached = r.z > 10;
  ok(!reached || (r.moon && /TO THE MOON/.test(r.txt) && r.top.some(e => e.moon)), 'moon flag on result + local board (zone ' + r.z + '): ' + r.txt);
  ok(!reached || r.ach.includes('moon'), 'TO THE MOON achievement unlocked: ' + r.ach.join(','));
  await ev(p, () => __decicat.advance(60));
  ok(await tapUI(p, 'share'), 'SHARE ON X button present');
  const url = await ev(p, () => __decicat.v5.lastShare);
  ok(url && url.startsWith('https://x.com/intent/post?text=') && url.includes(encodeURIComponent('https://decicat.bitcade.xyz/play')) && decodeURIComponent(url).includes('Can you beat me?'), 'share opens x.com/intent/post with text + bitcade URL');
  await ev(p, () => __decicat.achReset());
  await p.context().close();
}
// 6. share text for a normal run
{
  const p = await page('?nogate&manual&autostart&seed=9&zone=1&offline');
  await ev(p, () => { __decicat.advance(200); __decicat.kill(); });
  for (let i = 0; i < 40 && await ev(p, () => !__decicat.result || __decicat.result.pending); i++) { await ev(p, () => __decicat.advance(10)); await p.waitForTimeout(50); }
  const t = await ev(p, () => __decicat.shareText());
  ok(/^I survived \d+:\d\d and reached Stage 1 in DECICAT .+ Can you beat me\?$/u.test(t), 'share text: ' + t);
  await p.context().close();
}
// 7. achievements: toast on unlock, persisted, trophies view with pages; skins gated + picker
{
  const p = await page('?manual&nogate');
  await ev(p, () => __decicat.achReset());
  const p2 = await p.context().newPage(); p2.on('pageerror', e => errs.push('p2 ' + e.message)); await p2.goto(URL0 + '?manual&autostart&seed=2&zone=1'); await p2.waitForTimeout(300);
  await ev(p2, () => { __decicat.advance(30); __decicat.press(); __decicat.advance(10); __decicat.release(); __decicat.advance(5); });
  const a = await ev(p2, () => __decicat.v5);
  ok(a.ach.includes('hop') && a.toasts > 0, 'FIRST HOP unlocks with a toast');
  await p2.close();
  await p.reload(); await p.waitForTimeout(500); await ev(p, () => __decicat.advance(130));
  ok(await ev(p, () => __decicat.v5.ach.includes('hop')), 'achievements persist in localStorage');
  await tapUI(p, 'skinR'); ok(await ev(p, () => __decicat.v5.skin) === 'classic', 'locked skins cannot be picked');
  await ev(p, () => { const s = JSON.parse(localStorage.getItem('decicat_ach_v1')); s.storm = 1; s.moon = 1; localStorage.setItem('decicat_ach_v1', JSON.stringify(s)); });
  await p.reload(); await p.waitForTimeout(500); await ev(p, () => __decicat.advance(130));
  const sk = []; for (let i = 0; i < 3; i++) { await tapUI(p, 'skinR'); sk.push(await ev(p, () => __decicat.v5.skin)); }
  ok(sk.join(',') === 'night,astro,classic', 'picker cycles unlocked skins only: ' + sk.join(','));
  ok(await ev(p, () => localStorage.getItem('decicat_skin')) === 'classic', 'skin choice saved');
  await tapUI(p, 'ach'); ok(await ev(p, () => __decicat.state) === 'ach', 'TROPHIES opens the trophies view');
  await tapUI(p, 'next'); ok(await ev(p, () => __decicat.achPage) === 1, 'trophies page 2');
  await tapUI(p, 'back'); ok(await ev(p, () => __decicat.state) === 'title', 'BACK returns to the title');
  const frames = await ev(p, () => ['classic', 'night', 'hoodie', 'gold', 'laser', 'astro'].map(id => { const f = __decicat.skin(id); return f && f.idle ? f.idle.width + 'x' + f.idle.height : null; }));
  ok(frames.every(f => f === frames[0]), 'every skin builds sprites from the traced cat (' + frames[0] + ')');
  await ev(p, () => __decicat.achReset());
  await p.context().close();
}
// 8. phone + 480 title/game over render without errors (credits wrap on narrow screens)
for (const vp of [{ width: 390, height: 844 }, { width: 480, height: 480 }, { width: 320, height: 568 }]) {
  const p = await page('?manual&nogate', vp); await ev(p, () => __decicat.advance(130));
  await ev(p, () => { __decicat.start(); __decicat.advance(120); __decicat.kill(); }); for (let i = 0; i < 20; i++) { await ev(p, () => __decicat.advance(10)); await p.waitForTimeout(30); }
  ok(await ev(p, () => __decicat.state) === 'over', `game over renders at ${vp.width}x${vp.height}`);
  await p.context().close();
}
ok(errs.length === 0, 'no console/page errors' + (errs.length ? ': ' + errs.slice(0, 4).join(' | ') : ''));
await b.close(); console.log(fails ? fails + ' FAILED' : 'ALL PASS'); process.exit(fails ? 1 : 0);
